language: rust
sudo: false
cache: cargo

branches:
  only:
    - master
    - staging
    - trying

matrix:
  fast_finish: true

  include:
    # This is the minimum Rust version supported by find-crate.
    # When updating this, the reminder to update the minimum required version in README.md.
    # - rust: 1.15.1 # https://github.com/dtolnay/syn/blob/master/.travis.yml
    #   script:
    #     - cargo build

    - rust: stable
    - rust: beta
    - rust: nightly
      script:
        - cargo test

    - rust: nightly
      name: cargo check (minimal versions)
      script:
        - cargo update -Zminimal-versions
        - cargo check

    - rust: nightly
      name: cargo clippy
      script:
        - rustup component add clippy || travis_terminate 0
        - cargo clippy --all --all-features

    - rust: stable
      name: cargo fmt
      script:
        - rustup component add rustfmt
        - cargo fmt -- --check

    - rust: nightly
      name: cargo doc
      script:
        - RUSTDOCFLAGS=-Dwarnings cargo doc --no-deps

env:
  - RUSTFLAGS="-D warnings"

before_script:
  - set -o errexit

script:
  - cargo test --tests

notifications:
  email:
    on_success: never
