language: rust
sudo: false
cache: cargo

matrix:
  fast_finish: true

  include:
    # This is the minimum Rust version supported by find-crate.
    # When updating this, the reminder to update the minimum required version in README.md.
    - rust: 1.15.1 # https://github.com/dtolnay/syn/blob/master/.travis.yml

    - rust: stable
    - rust: beta
    - rust: nightly
      script:
        - cargo test

    - rust: nightly
      name: cargo test (minimal versions)
      script:
        - cargo update -Zminimal-versions
        - cargo test

    - rust: nightly
      name: cargo clippy
      script:
        - if rustup component add clippy;
          then
            cargo clippy -- -Dwarnings;
          else
            echo 'Skipping clippy';
          fi

    - rust: stable
      name: cargo fmt
      script:
        - rustup component add rustfmt
        - cargo fmt -- --check

    - rust: nightly
      name: cargo doc
      script:
        - RUSTDOCFLAGS=-Dwarnings cargo doc --no-deps

before_script:
  - set -o errexit

script:
  - cargo test --tests

notifications:
  email:
    on_success: never
